# Netlify configuration file

[build]
  publish = "dist"
  command = "npm run build"

# Cache control headers for different file types
[[headers]]
  # Cache HTML files for a short time (10 minutes)
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  # Cache CSS and JavaScript files for a longer time (1 week)
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  # Cache JavaScript files for a longer time (1 week)
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  # Cache images, fonts, and other static assets for a very long time (1 year)
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache images for a very long time (1 year)
  for = "/*.{jpg,jpeg,png,gif,webp,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache fonts for a very long time (1 year)
  for = "/*.{woff,woff2,ttf,otf,eot}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect all routes to index.html for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
